name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      mapbender_version:
        description: 'Mapbender version'
        required: true
        default: '3.3.3'


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v1
      with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --build-arg MAPBENDER_VERSION='${{ github.event.inputs.mapbender_version }}' --tag ghcr.io/miathedev/docker-mapbender3:'${{ github.event.inputs.mapbender_version }}'
        docker push ghcr.io/miathedev/docker-mapbender3:'${{ github.event.inputs.mapbender_version }}'
